import * as fs from 'fs';
import * as config from 'config';
import { UpdateUserPermission } from 'synapsepay';
const encodedPdf = fs.readFileSync(`${process.cwd()}/legal-agreement.b64`, 'utf8');
const licenseMimetypes = ['image/jpg', 'image/jpeg', 'image/png'];

const DELETE_USER_PERMISSION: UpdateUserPermission = 'CLOSED';
const SYNAPSEPAY_INVALID_OR_EXPIRED_OAUTH_KEY_ERROR_CODE = '300';
const SYNAPSEPAY_USER_FINGERPRINT_ERROR_CODE = '10';
const SYNAPSEPAY_TOO_MANY_REQUESTS_ERROR_STATUS_CODE = 429;

const {
  clientId: SYNAPSEPAY_CLIENT_ID,
  clientSecret: SYNAPSEPAY_SECRET,
  environment: SYNAPSEPAY_ENVIRONMENT,
  feeNodeId: SYNAPSEPAY_FEE_NODE_ID,
  hostUrl: SYNAPSEPAY_HOST_URL,
  disbursingNodeId: SYNAPSEPAY_DISBURSING_NODE_ID,
  disbursingUserId: SYNAPSEPAY_DISBURSING_USER_ID,
  disbursingUserFingerprint: SYNAPSEPAY_DISBURSING_USER_FINGERPRINT,
  userFingerprintSecret: SYNAPSEPAY_USER_FINGERPRINT_SECRET,
  alternateFingerprintSecret: SYNAPSEPAY_ALTERNATE_FINGERPRINT_SECRET,
  userFingerprintRedisKey: SYNAPSEPAY_USER_FINGERPRINT_REDIS_KEY,
  disbursingNodeIdACH: SYNAPSEPAY_DISBURSING_NODE_ID_ACH,
  receivingNodeIdACH: SYNAPSEPAY_RECEIVING_NODE_ID_ACH,
  useNewACH,
} = config.get('synapsepay');

const SYNAPSEPAY_DISBURSING_USER_CACHE_KEY = `dave_synapsepay_user_${SYNAPSEPAY_DISBURSING_USER_ID}`;

const SYNAPSEPAY_RECEIVING_NODE_TYPE = useNewACH ? 'ACH-US' : 'DEPOSIT-US';

const SYNAPSEPAY_RECEIVING_NODE_ID = useNewACH
  ? SYNAPSEPAY_RECEIVING_NODE_ID_ACH
  : config.get('synapsepay.receivingNodeId');

const SYNAPSEPAY_SUBSCRIPTION_RECEIVING_NODE_TYPE = config.has(
  'synapsepay.receivingNodeSubscriptions',
)
  ? 'ACH-US'
  : SYNAPSEPAY_RECEIVING_NODE_TYPE;

const SYNAPSEPAY_SUBSCRIPTION_RECEIVING_NODE_ID = config.has(
  'synapsepay.receivingNodeSubscriptions',
)
  ? config.get('synapsepay.receivingNodeSubscriptions')
  : SYNAPSEPAY_RECEIVING_NODE_ID;

export default {
  encodedPdf,
  licenseMimetypes,
  SYNAPSEPAY_HOST_URL,
  SYNAPSEPAY_RECEIVING_NODE_TYPE,
  SYNAPSEPAY_DISBURSING_NODE_TYPE: 'ACH-US',
  SYNAPSEPAY_ENVIRONMENT,
  SYNAPSEPAY_CLIENT_ID,
  SYNAPSEPAY_SECRET,
  SYNAPSEPAY_RECEIVING_NODE_ID,
  SYNAPSEPAY_SUBSCRIPTION_RECEIVING_NODE_ID,
  SYNAPSEPAY_SUBSCRIPTION_RECEIVING_NODE_TYPE,
  SYNAPSEPAY_DISBURSING_NODE_ID: useNewACH
    ? SYNAPSEPAY_DISBURSING_NODE_ID_ACH
    : SYNAPSEPAY_DISBURSING_NODE_ID,
  SYNAPSEPAY_DISBURSING_USER_ID,
  SYNAPSEPAY_DISBURSING_USER_FINGERPRINT,
  SYNAPSEPAY_FEE_NODE_ID,
  DELETE_USER_PERMISSION,
  SYNAPSEPAY_USER_FINGERPRINT_SECRET,
  SYNAPSEPAY_ALTERNATE_FINGERPRINT_SECRET,
  SYNAPSEPAY_INVALID_OR_EXPIRED_OAUTH_KEY_ERROR_CODE,
  SYNAPSEPAY_USER_FINGERPRINT_ERROR_CODE,
  SYNAPSEPAY_TOO_MANY_REQUESTS_ERROR_STATUS_CODE,
  SYNAPSEPAY_USER_FINGERPRINT_REDIS_KEY,
  SYNAPSEPAY_DISBURSING_USER_CACHE_KEY,
};
