version: '3'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '46379:6379'
    logging:
      driver: none
  mysql:
    image: 'mysql:5.7'
    command: "--character-set-server='utf8mb4' --collation-server='utf8mb4_unicode_ci'"
    ports:
      - '53307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: dave_dev
  pubsub-emulator:
    ports:
      - '8682:8681'
    image: 'messagebird/gcloud-pubsub-emulator:latest'
    environment:
      PUBSUB_PROJECT1: dave-staging-173321,test_plaid-update:test_plaid-updater,test_balance_log,test_synapsepay-update-user:test_overdraft-synapsepay-update-user,test_bank_connection_update,test_bank-connection-update-completed,test_advance-approval-ml-score-preprocess:test_advance-approval-ml-score-preprocess,test_advance-approval-ml-score,test_daily-balance-log,test_new-recurring-transaction,test_user-updated,test_record-created,test_tabapay-chargeback
      PUBSUB_PROJECT2: bank-project-217719,bank-testing:my-test-sub,debit-cards-staging:overdraft-api-debit-cards-dev,account-created:account-created
