apiVersion: batch/v1
kind: Job
metadata:
  name: {{LOWER_NAME}}
spec:
  template:
    spec:
      restartPolicy: Never
      nodeSelector:
        cloud.google.com/gke-nodepool: task-pool-high-cpu
      containers:
        - name: {{LOWER_NAME}}
          imagePullPolicy: Always
          image: 'us.gcr.io/dave-173321/api-dave-v2:latest'
          command: ['node','dist/bin/scripts/{{SCRIPT_NAME}}.js'{{SCRIPT_ARGUMENTS}}]
          resources:
            limits:
              memory: "25Gi"
            requests:
              memory: "25Gi"
          env:
            - name: NODE_ENV
              value: production
            - name: PROJECT_ID
              value: dave-173321
            - name: DEPLOYMENT_NAME
              value: {{SCRIPT_NAME}}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DD_TRACE_AGENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          envFrom:
            - secretRef:
                name: dave-secrets
            - configMapRef:
                name: default-dave-config
