const tabapayResponseCodes: { [key: string]: string } = {
  '00': 'Approved or completed successfully',
  '01': 'Refer to card issuer',
  '02': 'Refer to card issuers special conditions',
  '03': 'Invalid merchant',
  '04': 'Pick-up',
  '05': 'Do not honor',
  '06': 'Error',
  '07': 'Pick-up card, special conditions',
  '08': 'Honor with identification',
  '09': 'Request in progress',
  10: 'Approved for partial amount',
  11: 'Approved (VIP)',
  12: 'Invalid transaction',
  13: 'Invalid amount',
  14: 'Invalid card number (no such number)',
  15: 'No such issuer',
  16: 'Approved, update track 3',
  17: 'Customer cancellation, reversal (unsupported)',
  18: 'Customer dispute, chargeback (future)',
  19: 'Re-enter transaction',
  20: 'Invalid response',
  21: 'No action taken, reversal (unsupported)',
  22: 'Suspected malfunction, reversal (unsupported)',
  23: 'Unacceptable transaction fee',
  24: 'File update not supported by receiver',
  25: 'Unable to locate record on file',
  26: 'Duplicate file update record, no action',
  27: 'File update field edit error',
  28: 'File update record locked out',
  29: 'File update not successful, contact acquirer',
  30: 'Format error (may also be a reversal)',
  31: 'Bank not supported by switch',
  32: 'Completed partially, reversal (unsupported)',
  33: 'Expired card, pick-up',
  34: 'Suspected fraud, pick-up',
  35: 'Card acceptor contact acquirer, pick-up',
  36: 'Restricted card, pick-up',
  37: 'Card acceptor call acquirer security, pick-up',
  38: 'Allowable PIN tries exceeded, pick-up',
  39: 'No credit account',
  40: 'Requested function not supported',
  41: 'Lost card, pick-up',
  42: 'No universal account',
  43: 'Stolen card, pick-up',
  44: 'No investment account',
  45: 'Reserved for ISO use',
  46: 'Reserved for ISO use',
  47: 'Reserved for ISO use',
  48: 'Reserved for ISO use',
  49: 'Reserved for ISO use',
  50: 'Reserved for ISO use',
  51: 'Insufficient funds',
  52: 'No checking account',
  53: 'No savings account',
  54: 'Expired card',
  55: 'Incorrect PIN',
  56: 'No card record',
  57: 'Transaction not permitted to cardholder',
  58: 'Transaction not permitted to terminal (may also be a chargeback)',
  59: 'Suspected fraud',
  60: 'Card acceptor contact acquirer',
  61: 'Exceeds withdrawal amount limit',
  62: 'Restricted card',
  63: 'Security violation (may also be a chargeback)',
  64: 'Original amount incorrect, reversal (unsupported)',
  65: 'Exceeds withdrawal frequency limit',
  66: 'Card acceptor call acquirer security',
  67: 'Hard capture, pick-up',
  68: 'Response received too late, reversal (unsupported)',
  69: 'Reserved for ISO',
  70: 'Reserved for ISO',
  71: 'Reserved for ISO',
  72: 'Reserved for ISO',
  73: 'Reserved for ISO',
  74: 'Reserved for ISO',
  75: 'Allowable number of PIN tries exceeded',
  76: 'Key synchronization error (FIS)',
  77: 'Reserved for private use',
  78: 'Customer not eligible for POS (Star SM )',
  79: 'Invalid digital signature',
  80: 'Stale dated transaction (Star SM )',
  81: 'Issuer requested standin',
  82: 'Count exceeds limit (VISANet)',
  83: 'Reserved for private use',
  84: 'Time limit for pre-authorization reached (VISANet)',
  85: 'Issuer has no reason to decline the transaction (Account Verification)',
  86: 'Cannot verify PIN (VISANet)',
  87: 'Check already posted',
  88: 'Information not on file',
  89: 'Card verification value (CVV) verification failed (no pickup)',
  90: 'Cutoff is in progress',
  91: 'Issuer or switch is inoperative',
  92: 'Financial institution or intermediate network unknown for routing',
  93: 'Transaction cannot be completed, violation of law',
  94: 'Duplication transaction',
  95: 'Reconcile error',
  96: 'System malfunction',
  97: 'Reserved for national use',
  98: 'Reserved for national use',
  99: 'Card network fault error',
  E1: 'Invalid or unsupported SEC',
  E2: 'AVS data required',
  E3: 'CVV2 data required',
  E4: 'Service not allowed. Transaction not permitted to cardholder.',
  E5: 'Service not allowed. Transaction not permitted to cardholder.',
  E6: 'Issuer country is blocked',
  E7: 'Incorrect MAC was sent',
  E8: 'Standard Entry Class requirements were not met',
  E9: 'System time out',
  EA: 'Account length error',
  EB: 'Check digit error',
  EC: 'CID format error',
  ED: 'Authorization is too old to capture',
  EE: 'Card product code is blocked Card product code is blocked',
  EF: 'Attempt to process a BRIC transaction on a prior PIN based transaction',
  EG: 'CyberSource Time Out Connection to CyberSource timed out',
  EH: 'CARD_ENT_METH supplied is not valid or required additional data not provided as defined',
  EI: 'CARD_ID is not valid',
  EJ: 'Required PIN block not present',
  EK: 'Bin is not valid for pinless routing',
  EL: 'Signature store did not complete',
  EM: 'Debit PIN transactions must be swiped',
  EN: 'DB proxy response was not processed within the time out period',
  EO: 'Transaction was declined by merchant due to mismatch of CVV2 data',
  EP: 'Transaction not allowed as per a validation rule',
  EQ: 'There were no available gateway nodes to route transaction',
  N0: 'Authorization life cycle unacceptable',
  N1: 'Authorization life cycle expired',
  N2: 'Non-receipt of requested item (future)',
  N3: 'Non-receipt of requested item, illegible copy (future)',
  N4: 'Transaction exceeds floor limit (future)',
  N5: 'Declined authorization (future)',
  N6: 'Non-matching account numbers (future)',
  N7: 'Error in addition (future)',
  N8: 'Altered amount (future)',
  N9: 'Incorrect account number (future)',
  P0: 'Missing signature (future)',
  P1: 'Slip without card imprint (future)',
  P2: 'Imprinting of multiple slips (future)',
  P3: 'Canceled pre-authorization transaction (future)',
  P4: 'Delinquent settlement (future)',
  P5: 'Currency conversion error (future)',
  P6: 'Credit posted as a debit (sale) (future)',
  P7: 'Claim or defense (future)',
  P8: 'Non-receipt of goods (future)',
  P9: 'Defective merchandise (future)',
  Q1: 'Card authentication failed',
  R0: 'Fraudulent transaction prior to embossed valid date (future)',
  R1: 'Credit not received (future)',
  R2: 'Allowable PAN entries warning -- approved',
  R3: 'Approved with overdraft protection',
  R4: 'Bad CVV3',
  RR: 'Unknown Backend Processing Error',
  S0: 'Check not acceptable for cash',
  S1: 'Check not acceptable',
  S2: 'Check deposit limit exceeded',
  S3: 'Cash back limit exceeded',
  S4: 'Check amount does not match courtesy amount',
  S5: 'PIN not selected',
  S6: 'PIN already selected',
  S7: 'Unmatched voucher information',
  S8: 'Allowable PAN entries exceeded -- denial',
  S9: 'Expiration date mismatch',
  SA: 'Inactive card',
  SB: 'Expiration date mismatch (card pickup)',
  SC: 'Item suspected for stop pay',
  SD: 'Account closed',
  SE: 'Ineligible account',
  SF: 'Item submitted more than two times',
  SG: 'No account on file - absolute',
  SH: 'Unable to locate',
  SI: 'General denial',
  SJ: 'Item settled via ACH',
  SK: 'Cross-reference card not found',
  SL: 'Category limit exceeded',
  SM: 'Transaction limit exceeded',
  SN: 'Daily limit exceeded',
  SO: 'Monthly limit exceeded',
  SP: 'Invalid secret code',
  SQ: 'PIN key sync error',
  SR: 'Bad CVV2',
  SS: 'Stop payment order',
  ST: 'Revocation of authorization order',
  SV: 'Stop reoccurring payments',
  T3: 'Lost card (no pickup)',
  T4: 'Closed account',
  T5: 'Dormant account',
  T6: 'Special conditions (no pick-up)',
  T7: 'Purchase only approval for purchase with cash back transaction.',
  T9: 'Insufficient funds for fees',
  TA: 'ARQC validation failed for chip card',
  TB: 'Unsafe PIN',
  ZD: 'MasterCard Send (MoneySend) Error due to Expiration Date',
  ZN: 'MasterCard Send (MoneySend) Decline due to Card was Declined',
  ZR: 'MasterCard Send (MoneySend) Decline due to Unsupported Card',
  ZU: 'MasterCard Send (MoneySend) Error due to an Unknown Reason',
  ZX: 'MasterCard Send (MoneySend) Decline due to an Unknown Reason',
  ZY: 'MasterCard Send (MoneySend) Request in Unknown Status',
  ZZ: 'Used by TabaPay for Testing',
  '000': 'Approved',
  '001': 'Approved with identification',
  '002': 'Approved for partial amount',
  '003': 'Approved (VIP)',
  100: 'Do not honor',
  200: 'Do not honor',
  101: 'Expired card',
  201: 'Expired card',
  102: 'Suspected fraud',
  202: 'Suspected fraud',
  103: 'Card acceptor contact acquirer',
  203: 'Card acceptor contact acquirer',
  104: 'Restricted card ',
  204: 'Restricted card',
  105: 'Card acceptor call acquirer’s security department',
  205: 'Card acceptor call acquirer’s security department',
  106: 'Allowable PIN tries exceeded ',
  206: 'Allowable PIN tries exceeded',
  107: 'Refer to card issuer',
  108: 'Refer to card issuer’s special condition',
  109: 'Invalid merchant',
  110: 'Invalid amount',
  111: 'Invalid card number',
  112: 'PIN data required',
  113: 'Unacceptable fee',
  114: 'No account of type requested',
  214: 'No account of type requested',
  115: 'Requested function not supported (invalid transaction)',
  116: 'Insufficient funds ',
  216: 'Insufficient funds',
  117: 'Incorrect PIN ',
  217: 'Incorrect PIN',
  118: 'No card record',
  119: 'Transaction not permitted to cardholder',
  120: 'Transaction not permitted to terminal',
  121: 'Exceeds withdrawal amount limit',
  122: 'Security violation',
  123: 'Exceeds withdrawal limit frequency',
  124: 'Violation of law',
  126: 'Invalid PIN block',
  127: 'PIN length error',
  128: 'PIN key synchronization error (sanity error)',
  129: 'Suspected counterfeit card',
  130: 'Transaction failed OFAC check',
  131: 'Check not acceptable',
  180: 'Limit exceeded due to cashback amount',
  181: 'Enter lesser amount',
  182: 'Institution not supported by switch',
  183: 'Balances not available for inquiry',
  184: 'Resubmission in violation of network rules',
  185: 'Stop payment on check (shared branch only)',
  207: 'Special conditions',
  208: 'Lost card',
  209: 'Stolen card',
  210: 'Suspected counterfeit card',
  907: 'Card issuer or switch inoperative',
  908: 'Transaction destination cannot be found for routing',
  909: 'System malfunction',
  999: 'Used by TabaPay for Testing',
};

export default tabapayResponseCodes;
