export const SIDE_HUSTLE_JOB_SORT_RANDOM = 'random';
export const SIDE_HUSTLE_JOB_SORT_ALPHA = 'alpha';
export const SIDE_HUSTLE_JOB_SORT_COST_PER_CLICK = 'costPerClick';
export const SIDE_HUSTLE_JOB_SORT_COST_PER_APPLICATION = 'costPerApplication';

export const SIDE_HUSTLE_SORT_FIELDS = [
  SIDE_HUSTLE_JOB_SORT_RANDOM,
  SIDE_HUSTLE_JOB_SORT_ALPHA,
  SIDE_HUSTLE_JOB_SORT_COST_PER_CLICK,
  SIDE_HUSTLE_JOB_SORT_COST_PER_APPLICATION,
];
